/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteRouteImport } from './routes/_base/route'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as BaseIndexRouteImport } from './routes/_base/index'
import { Route as BaseResgateIndexRouteImport } from './routes/_base/resgate/index'
import { Route as BaseExportarIndexRouteImport } from './routes/_base/exportar/index'

const BaseRouteRoute = BaseRouteRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRouteRoute,
} as any)
const BaseResgateIndexRoute = BaseResgateIndexRouteImport.update({
  id: '/resgate/',
  path: '/resgate/',
  getParentRoute: () => BaseRouteRoute,
} as any)
const BaseExportarIndexRoute = BaseExportarIndexRouteImport.update({
  id: '/exportar/',
  path: '/exportar/',
  getParentRoute: () => BaseRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/exportar/': typeof BaseExportarIndexRoute
  '/resgate/': typeof BaseResgateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/exportar': typeof BaseExportarIndexRoute
  '/resgate': typeof BaseResgateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_base': typeof BaseRouteRouteWithChildren
  '/_base/': typeof BaseIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_base/exportar/': typeof BaseExportarIndexRoute
  '/_base/resgate/': typeof BaseResgateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding/' | '/exportar/' | '/resgate/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/exportar' | '/resgate'
  id:
    | '__root__'
    | '/_base'
    | '/_base/'
    | '/onboarding/'
    | '/_base/exportar/'
    | '/_base/resgate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BaseRouteRoute: typeof BaseRouteRouteWithChildren
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRouteRoute
    }
    '/_base/resgate/': {
      id: '/_base/resgate/'
      path: '/resgate'
      fullPath: '/resgate/'
      preLoaderRoute: typeof BaseResgateIndexRouteImport
      parentRoute: typeof BaseRouteRoute
    }
    '/_base/exportar/': {
      id: '/_base/exportar/'
      path: '/exportar'
      fullPath: '/exportar/'
      preLoaderRoute: typeof BaseExportarIndexRouteImport
      parentRoute: typeof BaseRouteRoute
    }
  }
}

interface BaseRouteRouteChildren {
  BaseIndexRoute: typeof BaseIndexRoute
  BaseExportarIndexRoute: typeof BaseExportarIndexRoute
  BaseResgateIndexRoute: typeof BaseResgateIndexRoute
}

const BaseRouteRouteChildren: BaseRouteRouteChildren = {
  BaseIndexRoute: BaseIndexRoute,
  BaseExportarIndexRoute: BaseExportarIndexRoute,
  BaseResgateIndexRoute: BaseResgateIndexRoute,
}

const BaseRouteRouteWithChildren = BaseRouteRoute._addFileChildren(
  BaseRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BaseRouteRoute: BaseRouteRouteWithChildren,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
